project_name: substreams-sink

release:
  draft: true
  name_template: '{{.Tag}}'
  target_commitish: '{{ .Commit }}'

builds:
- skip: true

archives:
- format: binary

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"
